// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_family.sql

package database

import (
	"context"
)

const createFamily = `-- name: CreateFamily :one
INSERT INTO families (
  family_name
) VALUES (
  $1
) RETURNING id, family_name
`

func (q *Queries) CreateFamily(ctx context.Context, familyName string) (Family, error) {
	row := q.db.QueryRowContext(ctx, createFamily, familyName)
	var i Family
	err := row.Scan(&i.ID, &i.FamilyName)
	return i, err
}
