// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_user.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO learners (
  family_id,
  first_name,
  last_name,
  grade
) VALUES (
  $1,
  $2,
  $3,
  $4
) RETURNING id, family_id, first_name, last_name, grade, created_at, updated_at, image_url, learner_type
`

type CreateUserParams struct {
	FamilyID  int32
	FirstName string
	LastName  string
	Grade     sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Learner, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FamilyID,
		arg.FirstName,
		arg.LastName,
		arg.Grade,
	)
	var i Learner
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.FirstName,
		&i.LastName,
		&i.Grade,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.LearnerType,
	)
	return i, err
}
