// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type ActivitiesLearner struct {
	ID         int32
	LearnerID  int32
	ActivityID int32
}

type Activity struct {
	ID            int32
	Name          string
	Description   sql.NullString
	Purpose       sql.NullString
	StartDateTime sql.NullTime
	EndDateTime   sql.NullTime
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Family struct {
	ID         int32
	FamilyName string
}

type Learner struct {
	ID          int32
	FamilyID    int32
	FirstName   string
	LastName    string
	Grade       sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	ImageUrl    sql.NullString
	LearnerType sql.NullString
}
